vich_uploader:
    db_driver: orm

    mappings:
        portfolio_images:
            uri_prefix:         '%app.path.portfolio_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.portfolio_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        featured_images:
            uri_prefix: '%app.path.featured_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.featured_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_images:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        media_images:
            uri_prefix: '%app.path.media_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.media_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
