vich_uploader:
    db_driver: orm

    mappings:
        portfolio:
            uri_prefix: /images/portfolio
            upload_destination: '%kernel.project_dir%/public/images/portfolio'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
