controllers:
    resource: ../../src/Controller/
    type: annotation

administration:
    resource: ../../src/Administration/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
